feat(utils): created constructCssClass utility function
kickassCoderz/kickass-toolkit pull request #107
Opened 2023-04-27 08:23 UTC by Fazla-GroM

2023-04-27 14:48 UTC, capJavert requested changes
@Fazla-GroM looks good to me but wondering if we are solving anything with our implementation vs `classnames` or `clsx`. It is fine if we are just doing for the sake of implementation parity for our users but always curios if we can do something better.

On that point curious if other implementations use some kind of internal memoizations or if adding something like that would even bring additional performance. Just a 🥫 for 🧠

2023-04-27 14:48 UTC, capJavert commented on packages/utils/src/misc/constructCssClass/constructCssClass.ts
> +        }
I think this check is not needed since it will become string down the line with `stringStack.join`.

2023-04-27 14:48 UTC, capJavert commented on packages/utils/src/misc/constructCssClass/constructCssClass.ts
> +            const valueFromArray = Reflect.apply(constructCssClass, undefined, value)
Why not just `constructCssClass(value)`?

2023-04-27 14:48 UTC, capJavert commented on packages/utils/src/misc/constructCssClass/constructCssClass.ts
> +    for (const value of values) {
Since this is utility function which will be called a bunch of time during renders maybe just use plain `for` because at the end it is most performant vs `forEach` and `for of`?

2023-04-27 14:48 UTC, capJavert commented on packages/utils/src/misc/constructCssClass/constructCssClass.ts
> +            for (const [objectKey, objectValue] of objectEntries) {
Maybe also use basic `for` as my other comment suggests for top level.

2023-04-27 14:48 UTC, capJavert commented on packages/utils/src/misc/constructCssClass/constructCssClass.ts
> +        }
Just want to save on any computation since this function will be called a bunch of times during rendering like React.

2023-05-04 06:29 UTC, Fazla-GroM commented on packages/utils/src/misc/constructCssClass/constructCssClass.ts
> +            const valueFromArray = Reflect.apply(constructCssClass, undefined, value)
Because of infinite loop. 
If we call `constructCssClass` with array as value it will again enter in the same if condition. 
`Reflect.apply` calls the same method with array value as argument. 
For example:
`Reflect.apply(constructCssClass,undefined,[1,2,3])` is equal to `constructCssClass(1,2,3)`.

The other way to tackle this would be to use spread operator but in theory(didn't tested it) it should be slower.

2023-05-04 07:14 UTC, Fazla-GroM commented
> @Fazla-GroM looks good to me but wondering if we are solving anything with our implementation vs `classnames` or `clsx`. It is fine if we are just doing for the sake of implementation parity for our users but always curios if we can do something better.
> 
> On that point curious if other implementations use some kind of internal memoizations or if adding something like that would even bring additional performance. Just a 🥫 for 🧠

@capJavert I've considered memoization but decided not to go this path.
Any memoization we introduce to this function would be applied globaly which could cause potential memory leak.
Consider big projects with hungreds, possibly tousands of components. every possible combination of class names would be stored in the same cache. This problem would be even more exagerated with arrays and objects because we should somehow deduce if the key really changed ( eg. deep compare object or array).

IMHO, memoization is something that end user (developer) should implement as he knows best when is the right time to use it an is aware of pros and cons of it's implementation

2023-05-04 07:19 UTC, capJavert approved these changes
@Fazla-GroM fine by me for memoization, it was more of a food for thought. I would like to see some benchmarks of our utility vs similar classnames and clsx just so we see where we stand.

2023-05-04 07:23 UTC, Fazla-GroM commented
> @Fazla-GroM fine by me for memoization, it was more of a food for thought. I would like to see some benchmarks of our utility vs similar classnames and clsx just so we see where we stand.

will do

2023-05-06 09:10 UTC, Fazla-GroM commented
@capJavert  shall we push it even more or we can merge it ?

2023-05-06 09:48 UTC, capJavert approved these changes
I think good enough for now. Minor comment.

2023-05-06 09:48 UTC, capJavert commented on packages/utils/src/misc/composeCssClass/composeCssClass.ts
> +                if (valueFromArray) {
Should this not be typeof undefined check, remember tests failing for me while exploring some optimizations.

2023-05-28 08:47 UTC, Fazla-GroM commented on packages/utils/src/misc/composeCssClass/composeCssClass.ts
> +                if (valueFromArray) {
well tests are good. As `valueFromArray` can be only `string || undefined` I dont see how explicitly typeof check is different from falsy check.

2023-05-28 08:48 UTC, merged